// ignore_for_file: avoid_print
//
// Generates `docs/national-trunk-prefixes.md` — the reference table of every
// region that uses a national trunk (NDD) prefix, read straight from
// libphonenumber metadata so it is complete and stays correct.
//
// Run from the package root:
//   dart run tool/gen_trunk_prefixes.dart > ../../docs/national-trunk-prefixes.md

import 'package:dlibphonenumber/dlibphonenumber.dart' as p;
import 'package:intl_phone_number_input/src/models/country_list.dart';

void main() {
  final util = p.PhoneNumberUtil.instance;

  final names = <String, String>{};
  final dialCodes = <String, String>{};
  for (final c in Countries.countryList) {
    final iso = c['alpha_2_code'] as String?;
    if (iso == null) continue;
    names[iso] = (c['en_short_name'] as String?) ?? iso;
    dialCodes[iso] = (c['dial_code'] as String?) ?? '';
  }

  final withPrefix = <List<String>>[];
  final withoutPrefix = <List<String>>[];

  final regions = util.supportedRegions.toList()..sort();
  for (final iso in regions) {
    String? ndd;
    try {
      ndd = util.getNddPrefixForRegion(iso, true);
    } catch (_) {
      ndd = null;
    }
    final name = names[iso] ?? iso;
    final dial = dialCodes[iso].orDial(util, iso);

    if (ndd != null && ndd.isNotEmpty) {
      withPrefix.add([iso, name, dial, ndd, _example(util, iso, ndd)]);
    } else {
      withoutPrefix.add([iso, name, dial]);
    }
  }

  final b = StringBuffer();
  b.writeln('# National trunk (NDD) prefixes by country');
  b.writeln();
  b.writeln('> Generated by `packages/intl_phone_number_input/tool/'
      'gen_trunk_prefixes.dart` from libphonenumber metadata '
      '(dlibphonenumber). Do not edit by hand — re-run the script.');
  b.writeln();
  b.writeln('`TrunkPrefix.strip()` auto-corrects input for the '
      '**${withPrefix.length}** regions in the first table. It never alters '
      'input for the **${withoutPrefix.length}** regions in the second, which '
      'declare no trunk prefix (a leading digit there is significant).');
  b.writeln();
  b.writeln('Correction is applied only when the number minus the prefix is a '
      'possible length for the region, so partially typed input is left alone.');
  b.writeln();
  b.writeln('## Regions with a trunk prefix (correction applies)');
  b.writeln();
  b.writeln('| ISO | Country | Dial code | Trunk prefix | Example correction |');
  b.writeln('|-----|---------|-----------|--------------|--------------------|');
  for (final r in withPrefix) {
    b.writeln('| ${r[0]} | ${r[1]} | ${r[2]} | `${r[3]}` | ${r[4]} |');
  }
  b.writeln();
  b.writeln('## Regions without a trunk prefix (input never altered)');
  b.writeln();
  b.writeln('| ISO | Country | Dial code |');
  b.writeln('|-----|---------|-----------|');
  for (final r in withoutPrefix) {
    b.writeln('| ${r[0]} | ${r[1]} | ${r[2]} |');
  }

  print(b.toString());
}

/// Builds a `0XXXXXXXXX -> XXXXXXXXX` illustration using a real example number
/// for the region, so the table shows the actual effect per country.
String _example(p.PhoneNumberUtil util, String iso, String ndd) {
  try {
    final example = util.getExampleNumberForType(
        regionCode: iso, type: p.PhoneNumberType.mobile);
    if (example == null) return '—';
    final nsn = util.getNationalSignificantNumber(example);
    if (nsn.isEmpty) return '—';
    return '`$ndd$nsn` → `$nsn`';
  } catch (_) {
    return '—';
  }
}

extension on String? {
  String orDial(p.PhoneNumberUtil util, String iso) {
    if (this != null && this!.isNotEmpty) return this!;
    try {
      final cc = util.getCountryCodeForRegion(iso);
      return cc == 0 ? '—' : '+$cc';
    } catch (_) {
      return '—';
    }
  }
}
